[package]
name = "actix-web-sample"
version = "0.1.0"
authors = ["hanada <suihakauso@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
tera = "1.0"
actix-files = "0.2.1" # 追加